import{a as P,S as v,i}from"./assets/vendor-CNqCr-V-.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const q="53640533-1ad844143519c7c1e76be4a36",R="https://pixabay.com/api/",f=15;async function m(o,t=1){const s={key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:f};return(await P.get(R,{params:s})).data}const h=document.querySelector(".gallery"),g=document.querySelector(".loader"),p=document.querySelector(".load-more"),M=new v(".gallery a",{captionsData:"alt",captionDelay:250});function y(o){const t=o.map(({webformatURL:s,largeImageURL:n,tags:e,likes:r,views:c,comments:S,downloads:E})=>`
<li class="gallery-item">
  <a class="gallery-link" href="${n}">
    <img class="gallery-image" src="${s}" alt="${e}" />
  </a>
  <div class="info">
    <p class="info-item"><b>Likes</b> ${r}</p>
    <p class="info-item"><b>Views</b> ${c}</p>
    <p class="info-item"><b>Comments</b> ${S}</p>
    <p class="info-item"><b>Downloads</b> ${E}</p>
  </div>
</li>`).join("");h.insertAdjacentHTML("beforeend",t),M.refresh()}function $(){h.innerHTML=""}function b(){g.classList.remove("is-hidden")}function L(){g.classList.add("is-hidden")}function w(){p.classList.remove("is-hidden")}function l(){p.classList.add("is-hidden")}const B=document.querySelector(".search-form"),O=document.querySelector(".load-more"),x=document.querySelector(".gallery");let u="",a=1,d=0;B.addEventListener("submit",A);O.addEventListener("click",_);async function A(o){o.preventDefault();const t=o.currentTarget.elements["search-text"].value.trim();if(!t){i.warning({message:"Please enter a search query",position:"topRight"});return}u=t,a=1,$(),l(),b();try{const s=await m(u,a),{hits:n,totalHits:e}=s;if(!n.length){i.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(n),d=Math.ceil(e/f),a<d?w():(l(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{i.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{L(),o.target.reset()}}async function _(){a+=1,l(),b();try{const o=await m(u,a),{hits:t}=o;if(!t.length){l(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}y(t),C(),a<d?w():(l(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{i.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{L()}}function C(){const o=x.firstElementChild;if(!o)return;const{height:t}=o.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
