import{a as P,S as q,i}from"./assets/vendor-CvjrmXAb.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const v="53640533-1ad844143519c7c1e76be4a36",R="https://pixabay.com/api/",f=15;async function m(o,t=1){const s={key:v,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:f};return(await P.get(R,{params:s})).data}const y=document.querySelector(".gallery"),g=document.querySelector(".loader"),h=document.querySelector(".load-more"),M=new q(".gallery a",{captionsData:"alt",captionDelay:250});function p(o){const t=o.map(({webformatURL:s,largeImageURL:n,tags:e,likes:r,views:l,comments:S,downloads:E})=>`
<li class="gallery-item">
  <a class="gallery-link" href="${n}">
    <img class="gallery-image" src="${s}" alt="${e}" />
  </a>
  <div class="info">
    <p class="info-item"><b>Likes</b> ${r}</p>
    <p class="info-item"><b>Views</b> ${l}</p>
    <p class="info-item"><b>Comments</b> ${S}</p>
    <p class="info-item"><b>Downloads</b> ${E}</p>
  </div>
</li>`).join("");y.insertAdjacentHTML("beforeend",t),M.refresh()}function $(){y.innerHTML=""}function b(){g.classList.remove("is-hidden")}function L(){g.classList.add("is-hidden")}function w(){h.style.display="block"}function a(){h.style.display="none"}const B=document.querySelector(".form"),O=document.querySelector(".load-more"),x=document.querySelector(".gallery");let u="",c=1,d=0;a();B.addEventListener("submit",A);O.addEventListener("click",_);async function A(o){o.preventDefault();const t=o.currentTarget.elements["search-text"].value.trim();if(!t){i.warning({message:"Please enter a search query",position:"topRight"});return}u=t,c=1,$(),a(),b();try{const s=await m(u,c),{hits:n,totalHits:e}=s;if(!n.length){i.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}p(n),d=Math.ceil(e/f),d>1?w():(a(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{i.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{L(),o.target.reset()}}async function _(){c+=1,a(),b();try{const o=await m(u,c),{hits:t}=o;if(!t.length){a(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}p(t),C(),c<d?w():(a(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{i.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{L()}}function C(){const o=x.firstElementChild;if(!o)return;const{height:t}=o.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
